<template><div><p>☀ <span class="category"><strong>食物总称：</strong></span>
<span class="vocabulary"><strong>food</strong></span> [fu:d]
<span class="definition">n. [U, C] 人或动物所吃的东西，即食物：</span>everyday, staple food 日常食物；主食 / organic food 有机食品 / the food industry 食品行业 / to eat the right foods 合理膳食</p>
<p><span class="vocabulary"><strong>carbohydrate</strong></span> [ˌkɑ:bəʊˈhaɪdreɪt; 美 ˌkɑ:rboʊ-]
<span class="definition">n. [pl.] carbohydrates 可指含碳水化合物的食物；淀粉质食物（如面包、土豆、大米等）：</span>carbohydrates such as bread, pasta or chips 碳水化合物食品，如面包、意大利面食或炸薯条</p>
<p><span class="vocabulary"><strong>taste</strong></span> [teɪst]
<span class="definition">n. [C, usually sing.] 少量供品尝的食物：</span>Just have a taste of this cheese. 尝一点儿这种奶酪吧。</p>
<p><span class="vocabulary"><strong>parcel</strong></span> ['pɑːsl]
<span class="definition">n. [C] [尤英] 包裹着的食品：</span>neat parcel 整齐的小食包 / pasta parcel 面食包</p>
<p><span class="vocabulary"><strong>cube</strong></span> [kju:b]
<span class="definition">n. [C] 立方体的东西（尤指食物）：</span>Cut the meat into cubes. 把肉切成丁儿。</p>
<p><span class="vocabulary"><strong>bite</strong></span> [baɪt]
<span class="definition">n. 1 [C]（从更大块食物上咬下的）一口食物：</span>to enjoy every bite 享受每一口食物 / She didn’t eat a bite of her dinner. 她一口饭也没吃。<span class="definition">2 [sing.] [非正式] a bite (to eat) 少量食物；简单的一餐：</span>It’s time to go home for a bite to eat. 该回家吃点东西了。/ to grab a quick bite of lunch 匆忙吃点儿午餐</p>
<p><span class="vocabulary"><strong>mouthful</strong></span> [ˈmaʊθfʊl]
<span class="definition">n. [C]（饮料或食物的）一口，一满口的量：</span>She took a mouthful of water. 她喝了一大口水。/ She gulped down a mouthful of coffee. 她咽下一大口咖啡。/ Chew each mouthful fully before the next bite. 将每一口充分咀嚼后，再吃下一口。/ She took a large mouthful of bread and started to read the letter. 她咬了一大口面包，然后开始读信。/ I choked on a mouthful of tea. 我喝茶呛了一口。/ He told the story between mouthfuls. 他一边吃着东西一边讲了这个故事。/ She answered through a mouthful of cake. 她嘴里含着蛋糕作了回答。</p>
<p><span class="vocabulary"><strong>slice</strong></span> [slaɪs]
<span class="definition">n. [C] 切下的食物薄片：</span>a slice of bread 一片面包 / Cut the meat into thin slices. 把肉切成薄片。/ cheese, lemon slice 奶酪片；柠檬片</p>
<p><span class="vocabulary"><strong>helping</strong></span> [ˈhelpɪŋ]
<span class="definition">n. [C] ~ (of sth) 进餐时给予某人的一份食物：</span>big, generous, heaping（美）, huge, large helping 大份食物；特大份的食物 / a generous helping of potatoes 一大份土豆 / small helping 小份食物 / double, extra, second helping 双份食物；额外的一份食物；第二份食物 / healthy helping 大份的食物 / The steak came with a healthy(= large) helping of fries. 牛排和一大份薯条一起端了上来。/ I had an extra helping of meat. 我多吃了一份肉。/ We all had a second helping of pie. 我们又都吃了一份馅饼。/ She gave them extra helpings of ice-cream. 她又给了他们几份冰激凌。</p>
<p><span class="vocabulary"><strong>second</strong></span> ['sekənd]
<span class="definition">n. [pl.] [非正式] seconds 可指吃过后再上的同种类的一份食物：</span>Seconds, anybody? 有谁需要再来一份吗？/ There are seconds if you want them. 你想要的话还有。</p>
<p><span class="vocabulary"><strong>seafood</strong></span> [ˈsi🖕d]
<span class="definition">n. [U] 海鲜，尤指甲壳类海鲜：</span>fresh seafood 新鲜的海味 / local seafood 地方海鲜特产 / seafood dish 海味菜肴 / a good wine to drink with fish or seafood dishes 适合配鱼或海鲜的好酒 / seafood cocktail, seafood platter, seafood salad 海味冷盘；海鲜拼盘；海鲜色拉 / seafood chowder, seafood soup, seafood stew（均尤美）杂烩海鲜汤；海鲜汤；烩海鲜 / seafood restaurant 海鲜餐厅</p>
<p><span class="vocabulary"><strong>snack</strong></span> [snæk]
<span class="definition">n. [C] [非正式]（通常指匆匆吃的）少量餐食，如点心、快餐（这种餐食做起来或吃起来比较快）；小吃、零嘴（如巧克力）：</span>I only have time for a snack at lunchtime. 中午，我的时间只够吃点心。/ Lunch was a snack in the fields. 午饭是在野外吃的便餐。/ light, little, small snack 小吃；点心 / quick snack 快餐；匆匆吃点东西 / We stopped for a quick snack. 我们停下来匆匆吃了点东西。/ healthy, nutritious snack 健康快餐；营养快餐 / salty, savoury/savory（尤英）snack 咸味点心；美味点心 / sugary, sweet snack 甜点 / Do you eat sweets, cakes or sugary snacks? 你吃糖果、蛋糕或甜点吗？/ cold, hot snack 冷食快餐；热食快餐 / bedtime（尤美）, late-night, lunch-time, mid-afternoon, mid-morning, midnight snack 睡前点心；宵夜；午间快餐；下午茶；上午茶点 / bar snack 酒吧小吃 / Do you serve bar snacks? 你这儿卖不卖快餐？/ Order bar snacks with your drinks. 叫点小吃配你的饮料吧。/ to stop for a snack 停下来吃点东西 / I made myself a light snack. 我为自己准备了些小吃。/ A bar service provides drinks and snacks throughout the day.吧台全天提供饮料和茶点。/ snack food 零食 / snack lunch, snack meal（均英）快餐午饭；快餐饭 / Most office staff prefer a snack lunch to a sit-down meal. 大部分办公室职员都喜欢快餐午饭而非在餐厅正式用餐。/ snack time 茶点时间 / snack bar, snack counter 快餐店；快餐柜台 / snack machine零食自动售货机 / I got a drink from the hotel snack machine. 我在宾馆的自动售货机上买了杯饮料。</p>
<p><span class="vocabulary"><strong>starter</strong></span> [ˈstɑ:tə(r); 美 ˈstɑ:rt-]
<span class="definition">n. [C] [尤英] [美式通常用appetizer]（主菜之前的）开胃小吃、开胃菜：</span>cold, hot starter 凉开胃菜；热开胃菜 / delicious, tasty starter 美味的开胃菜；可口的开胃菜 / Are you having a starter? 你想要开胃菜吗? / I’ve chosen a hot starter. 我选了一道热开胃菜。/ This dish can be served as a starter or a main course. 这道菜可以作开胃菜，也可以当主菜。</p>
<p><span class="vocabulary"><strong>appetizer</strong></span> [ˈæpɪtaɪzə(r)]
<span class="definition">n. [C] 餐前的少量开胃食物或饮料：</span>Seafood soup is a good appetizer. 海鲜汤是一道很好的开胃菜。/ chicken, mushroom, salmon appetizer 鸡肉做的开胃菜；蘑菇做的开胃菜；鲑鱼做的开胃菜 / Let's order appetizers. 咱们要几样开胃小菜吧。</p>
<p><span class="vocabulary"><strong>accompaniment</strong></span> [əˈkʌmpənimənt]
<span class="definition">n. [C] ~ (to sth) 佐餐的食物、饮品：</span>The wine makes a good accompaniment to fish dishes. 这种葡萄酒很适合作鱼菜的佐餐酒。/ This recipe makes a good accompaniment to ice-cream. 这道食谱适合搭配冰激凌。/ These wines also make a good accompaniment for vegetarian dishes. 这些葡萄酒配素菜吃也很好。</p>
<p><span class="vocabulary"><strong>delicacy</strong></span> [ˈdelɪkəsi]
<span class="definition">n. [C] 某地的特色佳肴、美味佳肴：</span>exotic, rare delicacy 异域的美食；罕见的美食 / Have you tried any of the local delicacies? 你品尝过当地的美食吗?/ We were served course after course of mouthwatering local delicacies. 一道又一道令人垂涎的当地佳肴端到了我们的面前。/ The eggs of this bird are considered a great delicacy. 这种鸟的蛋被视为美味佳肴。/ Smoked salmon was considered an expensive delicacy. 熏鲑鱼被认为是一道昂贵的珍馐。</p>
<p>周边词汇补充：
· order可指所点的食物；
· rations可指（给战士或食品短缺地区的人提供的）定量口粮；
· portion可指（足够一个人吃的）食物的一份。</p>
</div></template>


